/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Admin2030IndexRouteImport } from './routes/admin-2030.index'
import { Route as Admin2030DashboardRouteImport } from './routes/admin-2030.dashboard'
import { Route as Admin2030DashboardIndexRouteImport } from './routes/admin-2030.dashboard.index'
import { Route as Admin2030DashboardValuesRouteImport } from './routes/admin-2030.dashboard.values'
import { Route as Admin2030DashboardInitiativesRouteImport } from './routes/admin-2030.dashboard.initiatives'
import { Route as Admin2030DashboardImagesRouteImport } from './routes/admin-2030.dashboard.images'
import { Route as Admin2030DashboardGoalsRouteImport } from './routes/admin-2030.dashboard.goals'
import { Route as Admin2030DashboardContentRouteImport } from './routes/admin-2030.dashboard.content'
import { Route as Admin2030DashboardBoardRouteImport } from './routes/admin-2030.dashboard.board'
import { Route as Admin2030DashboardAssemblyRouteImport } from './routes/admin-2030.dashboard.assembly'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin2030IndexRoute = Admin2030IndexRouteImport.update({
  id: '/admin-2030/',
  path: '/admin-2030/',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin2030DashboardRoute = Admin2030DashboardRouteImport.update({
  id: '/admin-2030/dashboard',
  path: '/admin-2030/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin2030DashboardIndexRoute = Admin2030DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Admin2030DashboardRoute,
} as any)
const Admin2030DashboardValuesRoute =
  Admin2030DashboardValuesRouteImport.update({
    id: '/values',
    path: '/values',
    getParentRoute: () => Admin2030DashboardRoute,
  } as any)
const Admin2030DashboardInitiativesRoute =
  Admin2030DashboardInitiativesRouteImport.update({
    id: '/initiatives',
    path: '/initiatives',
    getParentRoute: () => Admin2030DashboardRoute,
  } as any)
const Admin2030DashboardImagesRoute =
  Admin2030DashboardImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => Admin2030DashboardRoute,
  } as any)
const Admin2030DashboardGoalsRoute = Admin2030DashboardGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => Admin2030DashboardRoute,
} as any)
const Admin2030DashboardContentRoute =
  Admin2030DashboardContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => Admin2030DashboardRoute,
  } as any)
const Admin2030DashboardBoardRoute = Admin2030DashboardBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => Admin2030DashboardRoute,
} as any)
const Admin2030DashboardAssemblyRoute =
  Admin2030DashboardAssemblyRouteImport.update({
    id: '/assembly',
    path: '/assembly',
    getParentRoute: () => Admin2030DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/contact': typeof ContactRoute
  '/governance': typeof GovernanceRoute
  '/reports': typeof ReportsRoute
  '/admin-2030/dashboard': typeof Admin2030DashboardRouteWithChildren
  '/admin-2030/': typeof Admin2030IndexRoute
  '/admin-2030/dashboard/assembly': typeof Admin2030DashboardAssemblyRoute
  '/admin-2030/dashboard/board': typeof Admin2030DashboardBoardRoute
  '/admin-2030/dashboard/content': typeof Admin2030DashboardContentRoute
  '/admin-2030/dashboard/goals': typeof Admin2030DashboardGoalsRoute
  '/admin-2030/dashboard/images': typeof Admin2030DashboardImagesRoute
  '/admin-2030/dashboard/initiatives': typeof Admin2030DashboardInitiativesRoute
  '/admin-2030/dashboard/values': typeof Admin2030DashboardValuesRoute
  '/admin-2030/dashboard/': typeof Admin2030DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/contact': typeof ContactRoute
  '/governance': typeof GovernanceRoute
  '/reports': typeof ReportsRoute
  '/admin-2030': typeof Admin2030IndexRoute
  '/admin-2030/dashboard/assembly': typeof Admin2030DashboardAssemblyRoute
  '/admin-2030/dashboard/board': typeof Admin2030DashboardBoardRoute
  '/admin-2030/dashboard/content': typeof Admin2030DashboardContentRoute
  '/admin-2030/dashboard/goals': typeof Admin2030DashboardGoalsRoute
  '/admin-2030/dashboard/images': typeof Admin2030DashboardImagesRoute
  '/admin-2030/dashboard/initiatives': typeof Admin2030DashboardInitiativesRoute
  '/admin-2030/dashboard/values': typeof Admin2030DashboardValuesRoute
  '/admin-2030/dashboard': typeof Admin2030DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/contact': typeof ContactRoute
  '/governance': typeof GovernanceRoute
  '/reports': typeof ReportsRoute
  '/admin-2030/dashboard': typeof Admin2030DashboardRouteWithChildren
  '/admin-2030/': typeof Admin2030IndexRoute
  '/admin-2030/dashboard/assembly': typeof Admin2030DashboardAssemblyRoute
  '/admin-2030/dashboard/board': typeof Admin2030DashboardBoardRoute
  '/admin-2030/dashboard/content': typeof Admin2030DashboardContentRoute
  '/admin-2030/dashboard/goals': typeof Admin2030DashboardGoalsRoute
  '/admin-2030/dashboard/images': typeof Admin2030DashboardImagesRoute
  '/admin-2030/dashboard/initiatives': typeof Admin2030DashboardInitiativesRoute
  '/admin-2030/dashboard/values': typeof Admin2030DashboardValuesRoute
  '/admin-2030/dashboard/': typeof Admin2030DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/beneficiaries'
    | '/contact'
    | '/governance'
    | '/reports'
    | '/admin-2030/dashboard'
    | '/admin-2030/'
    | '/admin-2030/dashboard/assembly'
    | '/admin-2030/dashboard/board'
    | '/admin-2030/dashboard/content'
    | '/admin-2030/dashboard/goals'
    | '/admin-2030/dashboard/images'
    | '/admin-2030/dashboard/initiatives'
    | '/admin-2030/dashboard/values'
    | '/admin-2030/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/beneficiaries'
    | '/contact'
    | '/governance'
    | '/reports'
    | '/admin-2030'
    | '/admin-2030/dashboard/assembly'
    | '/admin-2030/dashboard/board'
    | '/admin-2030/dashboard/content'
    | '/admin-2030/dashboard/goals'
    | '/admin-2030/dashboard/images'
    | '/admin-2030/dashboard/initiatives'
    | '/admin-2030/dashboard/values'
    | '/admin-2030/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/beneficiaries'
    | '/contact'
    | '/governance'
    | '/reports'
    | '/admin-2030/dashboard'
    | '/admin-2030/'
    | '/admin-2030/dashboard/assembly'
    | '/admin-2030/dashboard/board'
    | '/admin-2030/dashboard/content'
    | '/admin-2030/dashboard/goals'
    | '/admin-2030/dashboard/images'
    | '/admin-2030/dashboard/initiatives'
    | '/admin-2030/dashboard/values'
    | '/admin-2030/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeneficiariesRoute: typeof BeneficiariesRoute
  ContactRoute: typeof ContactRoute
  GovernanceRoute: typeof GovernanceRoute
  ReportsRoute: typeof ReportsRoute
  Admin2030DashboardRoute: typeof Admin2030DashboardRouteWithChildren
  Admin2030IndexRoute: typeof Admin2030IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-2030/': {
      id: '/admin-2030/'
      path: '/admin-2030'
      fullPath: '/admin-2030/'
      preLoaderRoute: typeof Admin2030IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-2030/dashboard': {
      id: '/admin-2030/dashboard'
      path: '/admin-2030/dashboard'
      fullPath: '/admin-2030/dashboard'
      preLoaderRoute: typeof Admin2030DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-2030/dashboard/': {
      id: '/admin-2030/dashboard/'
      path: '/'
      fullPath: '/admin-2030/dashboard/'
      preLoaderRoute: typeof Admin2030DashboardIndexRouteImport
      parentRoute: typeof Admin2030DashboardRoute
    }
    '/admin-2030/dashboard/values': {
      id: '/admin-2030/dashboard/values'
      path: '/values'
      fullPath: '/admin-2030/dashboard/values'
      preLoaderRoute: typeof Admin2030DashboardValuesRouteImport
      parentRoute: typeof Admin2030DashboardRoute
    }
    '/admin-2030/dashboard/initiatives': {
      id: '/admin-2030/dashboard/initiatives'
      path: '/initiatives'
      fullPath: '/admin-2030/dashboard/initiatives'
      preLoaderRoute: typeof Admin2030DashboardInitiativesRouteImport
      parentRoute: typeof Admin2030DashboardRoute
    }
    '/admin-2030/dashboard/images': {
      id: '/admin-2030/dashboard/images'
      path: '/images'
      fullPath: '/admin-2030/dashboard/images'
      preLoaderRoute: typeof Admin2030DashboardImagesRouteImport
      parentRoute: typeof Admin2030DashboardRoute
    }
    '/admin-2030/dashboard/goals': {
      id: '/admin-2030/dashboard/goals'
      path: '/goals'
      fullPath: '/admin-2030/dashboard/goals'
      preLoaderRoute: typeof Admin2030DashboardGoalsRouteImport
      parentRoute: typeof Admin2030DashboardRoute
    }
    '/admin-2030/dashboard/content': {
      id: '/admin-2030/dashboard/content'
      path: '/content'
      fullPath: '/admin-2030/dashboard/content'
      preLoaderRoute: typeof Admin2030DashboardContentRouteImport
      parentRoute: typeof Admin2030DashboardRoute
    }
    '/admin-2030/dashboard/board': {
      id: '/admin-2030/dashboard/board'
      path: '/board'
      fullPath: '/admin-2030/dashboard/board'
      preLoaderRoute: typeof Admin2030DashboardBoardRouteImport
      parentRoute: typeof Admin2030DashboardRoute
    }
    '/admin-2030/dashboard/assembly': {
      id: '/admin-2030/dashboard/assembly'
      path: '/assembly'
      fullPath: '/admin-2030/dashboard/assembly'
      preLoaderRoute: typeof Admin2030DashboardAssemblyRouteImport
      parentRoute: typeof Admin2030DashboardRoute
    }
  }
}

interface Admin2030DashboardRouteChildren {
  Admin2030DashboardAssemblyRoute: typeof Admin2030DashboardAssemblyRoute
  Admin2030DashboardBoardRoute: typeof Admin2030DashboardBoardRoute
  Admin2030DashboardContentRoute: typeof Admin2030DashboardContentRoute
  Admin2030DashboardGoalsRoute: typeof Admin2030DashboardGoalsRoute
  Admin2030DashboardImagesRoute: typeof Admin2030DashboardImagesRoute
  Admin2030DashboardInitiativesRoute: typeof Admin2030DashboardInitiativesRoute
  Admin2030DashboardValuesRoute: typeof Admin2030DashboardValuesRoute
  Admin2030DashboardIndexRoute: typeof Admin2030DashboardIndexRoute
}

const Admin2030DashboardRouteChildren: Admin2030DashboardRouteChildren = {
  Admin2030DashboardAssemblyRoute: Admin2030DashboardAssemblyRoute,
  Admin2030DashboardBoardRoute: Admin2030DashboardBoardRoute,
  Admin2030DashboardContentRoute: Admin2030DashboardContentRoute,
  Admin2030DashboardGoalsRoute: Admin2030DashboardGoalsRoute,
  Admin2030DashboardImagesRoute: Admin2030DashboardImagesRoute,
  Admin2030DashboardInitiativesRoute: Admin2030DashboardInitiativesRoute,
  Admin2030DashboardValuesRoute: Admin2030DashboardValuesRoute,
  Admin2030DashboardIndexRoute: Admin2030DashboardIndexRoute,
}

const Admin2030DashboardRouteWithChildren =
  Admin2030DashboardRoute._addFileChildren(Admin2030DashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeneficiariesRoute: BeneficiariesRoute,
  ContactRoute: ContactRoute,
  GovernanceRoute: GovernanceRoute,
  ReportsRoute: ReportsRoute,
  Admin2030DashboardRoute: Admin2030DashboardRouteWithChildren,
  Admin2030IndexRoute: Admin2030IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
